module: default
runtime: custom
vm: true
threadsafe: true
handlers:
- url: /api/internal/.*
  script: IGNORED
  secure: always
  login: admin
  auth_fail_action: unauthorized
- url: /.*
  script: IGNORED
  secure: always
automatic_scaling:
  min_num_instances: 1
  max_num_instances : 2
health_check:
  enable_health_check: False
env_variables:
  idpServiceDbKeyspaceName: 'idot-service'